### ISSUE TITLE
Memory issue within Notification Extension

### ISSUE THREAD

**Issue by Razdel** [BelledonneCommunications/linhome-ios#1]
Hi! Notification extension crashes on iterate() method of core with 'EXC_RESOURCE RESOURCE_TYPE_MEMORY (limit=24 MB, unused=0x0)' message. It seems core exceeds the extension memory limit. If it runs with 'allocate' xcode instrument it shows memory allocation peak when push has been received while incoming call and it looks like mediastramer2 uses that memory.

**Comment by jehandelalune** [comment]
What is with video early media ?in case of early media video, memory consumption may be too high. Make sure to use h264 to limit memory usage

**Comment by cdeschambc** [comment]
Hello, 
we encountered such issues in early days  of Linhome when VP8 was enabled in extension. But we have now put a mechanism in place to disable it there. 
If this issue is still accurate you please make a new test with latest LInhome (1.3) and reopen with a log file. 
kind regards
