### ISSUE TITLE
error in building project

### ISSUE THREAD

**Issue by ashwani280496** [BelledonneCommunications/linhome-ios#2]
CpResource /Users/nestap/Documents/linhome-ios/Resources/linhome.zip /Users/nestap/Library/Developer/Xcode/DerivedData/Linhome-diclkxhulszjmaferfsavozpxgrx/Build/Products/Debug-iphoneos/LinhomeServiceExtension.appex/linhome.zip (in target 'LinhomeServiceExtension' from project 'Linhome')
    cd /Users/nestap/Documents/linhome-ios
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/nestap/Documents/linhome-ios/Resources/linhome.zip /Users/nestap/Library/Developer/Xcode/DerivedData/Linhome-diclkxhulszjmaferfsavozpxgrx/Build/Products/Debug-iphoneos/LinhomeServiceExtension.appex

error: /Users/nestap/Documents/linhome-ios/Resources/linhome.zip: No such file or directory (in target 'LinhomeServiceExtension' from project 'Linhome')

**Comment by cdescham** [comment]
Hello, 
The ZIP is built automatically, you need to pull the linhome-shared-theme submodule (git submodule update --init --recursive)

**Comment by cdeschambc** [comment]
Hello, 
this is an identified issue on our side (the synchronisation of the shared theme repository is not performed with GitHub)
cf https://github.com/BelledonneCommunications/linhome-android/issues/27

**Comment by KyronNextLevel** [comment]
The issue is fixed. Thank you for pointing it out.
